#!/bin/bash

sudo apt update
sudo apt install make
sudo apt install pciutils
sudo apt install mesa-utils

cd /tmp
rm -rf /tmp/neofetch
git clone --branch merged-branch https://github.com/theofficialgman/neofetch.git --depth=1
cd neofetch
sudo make install
rm -rf /tmp/neofetch