#!/bin/bash

version=1.1.0

cd $HOME
cd Downloads
wget https://github.com/Legcord/Legcord/releases/download/v1.1.0/Legcord-1.1.0-linux-armv7l.deb
sudo dpkg -i Legcord-1.1.0-linux-armv7l.deb
rm Legcord-1.1.0-linux-armv7l.deb

